# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Orange Garden
title_cn: 吴健部落格
email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#Write an awesome description for your new site here. You can edit this
#line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.
description: 每一位程序员都有一颗匠人的心
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iwj.github.io" # the base hostname & protocol for your site
twitter_username: #jekyllrb
github_username: iwj

# Build settings
markdown: kramdown

# Wujian Config
permalink: /:title/
paginate: 10
paginate_path: "/page:num"
plugins: [jekyll-paginate]
